### ISSUE TITLE
Features of the 1st IOS launch version

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/readBroccoliSite#21]
We will initially launch IOS first and then work on Android.

1. Interactive sound effect 
2. Interactive animation
3. Interactive definition explaining animation
4. Interactive colour unlock 
5. Background music
6. Multiple languages (Spanish, Chinese, Korean, English, French, Japanese)
7. Animation without touching
8. Read to you(Story reading function when you hit play button)
9. Counting the number of times each user uses the Interactive features(Animation, Sound, Colour, Definition, Language change, Read to me -> all the Interactive features) -> need a page where we can see the data.

**Comment by anthonyjoeseph** [comment]
Moved to specific issues - 

https://github.com/anthonyjoeseph/readBroccoliSite/issues/23
https://github.com/anthonyjoeseph/readBroccoliSite/issues/24
https://github.com/anthonyjoeseph/readBroccoliSite/issues/25
